### ISSUE TITLE
NullPointerException in WearDataApiService.onConnected()

### ISSUE THREAD

**Issue by plegermi** [Marcus-L/cordova-androidwear-dataapi#1]
Cheers mate,
just discovered that your plugin will keep crashing if the application has not been started yet, but the service received an onDataChanged event.

WearDataApiService.onDataChanged() will log "onDataChanged but no DataListeners.", which is correct.
But after being connected to the DataApi, you are not checking if WearDataApiPlugin.WearDataApiPluginSingleton has been initialized. Consider adding a check in [WearDataApiService.](https://github.com/Marcus-L/cordova-androidwear-dataapi/blob/master/src/android/WearDataApiService.java#L27)

**Comment by Marcus-L** [comment]
Thanks for the suggestion @plegermi, how does that look? Oh, and welcome to GitHub!

**Comment by Marcus-L** [comment]
Published the update on npmjs.
